name: CardPro
options:
  bundleIdPrefix: com.lman
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  CardPro:
    type: application
    platform: iOS
    sources:
      - path: CardPro/Sources
      - path: CardPro/Resources
    settings:
      base:
        INFOPLIST_FILE: CardPro/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.lman.cardpro
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
    info:
      path: CardPro/Resources/Info.plist
      properties:
        CFBundleDisplayName: CardPro
        CFBundleName: CardPro
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NFCReaderUsageDescription: "CardPro uses NFC to share and receive business cards"
        NSContactsUsageDescription: "CardPro needs access to Contacts to save received business cards"
        NSCameraUsageDescription: "CardPro uses camera to scan QR codes"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations: {}
    entitlements:
      path: CardPro/Resources/CardPro.entitlements
      properties:
        com.apple.developer.nfc.readersession.formats:
          - NDEF
          - TAG
