name: CardPro
options:
  bundleIdPrefix: com.lman
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "HG5RRBKA8T"
    CODE_SIGN_STYLE: Automatic

targets:
  CardPro:
    type: application
    platform: iOS
    sources:
      - path: CardPro/Sources
      - path: CardPro/Resources
    settings:
      base:
        INFOPLIST_FILE: CardPro/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.lman.cardpro
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
    info:
      path: CardPro/Resources/Info.plist
      properties:
        CFBundleDisplayName: CardPro
        CFBundleName: CardPro
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSContactsUsageDescription: "CardPro needs access to Contacts to save received business cards"
        NSCameraUsageDescription: "CardPro uses camera to scan QR codes"
        NFCReaderUsageDescription: "CardPro uses NFC to read and write business cards to NFC tags"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations: {}
        UIBackgroundModes:
          - remote-notification
        LSSupportsOpeningDocumentsInPlace: false
        CFBundleDocumentTypes:
          - CFBundleTypeName: vCard
            CFBundleTypeRole: Viewer
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - public.vcard
          - CFBundleTypeName: Business Card Image
            CFBundleTypeRole: Viewer
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - public.jpeg
              - public.png
        UTImportedTypeDeclarations:
          - UTTypeIdentifier: public.vcard
            UTTypeDescription: vCard Contact
            UTTypeConformsTo:
              - public.text
            UTTypeTagSpecification:
              public.filename-extension:
                - vcf
              public.mime-type:
                - text/vcard
                - text/x-vcard
    entitlements:
      path: CardPro/Resources/CardPro.entitlements
      properties:
        com.apple.developer.nfc.readersession.formats:
          - NDEF
          - TAG
        com.apple.security.application-groups:
          - group.com.lman.cardpro
        # iCloud sync disabled for now - enable after testing basic features
        # com.apple.developer.icloud-services:
        #   - CloudKit
        # com.apple.developer.icloud-container-identifiers:
        #   - iCloud.com.lman.cardpro
    dependencies:
      - target: CardProWidget
        embed: true

  CardProWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: CardProWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lman.cardpro.widget
        INFOPLIST_FILE: CardProWidget/Info.plist
        SKIP_INSTALL: YES
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: CardProWidget/Info.plist
      properties:
        CFBundleDisplayName: CardPro Widget
        CFBundleName: CardProWidget
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    entitlements:
      path: CardProWidget/CardProWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.lman.cardpro
